# Generated by Django 3.2.7 on 2022-01-18 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('created_on', models.DateTimeField(auto_created=True)),
                ('room_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='房间号')),
                ('course_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course_describe', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdetail')),
            ],
        ),
    ]
