# Generated by Django 3.2.7 on 2022-01-28 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20220128_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 1, 28, 14, 31, 35, 864305, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='room_id',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='room_id',
            field=models.BigIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user_id',
            field=models.BigIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
